### ISSUE TITLE
rapid keyboard events (enter) cause a laggy behavior

### ISSUE THREAD

**Issue by AndersonCeci** [OpenCovenant/quill#103]
when pressing enter really fast it causes the cursor to lag and makes the cursor go to the line above where it is supposed to be the video explains it better 
[screen-capture (2).webm](https://user-images.githubusercontent.com/37506005/204110192-a2bbb6c6-6b0e-48ed-a02c-f84c1ad069be.webm)

**Comment by AndiBraimllari** [comment]
Feel free to close this @AndersonCeci if it works fine now.
