### ISSUE TITLE
broken file upload

### ISSUE THREAD

**Issue by AndersonCeci** [OpenCovenant/quill#104]
uploading files doesn't find any error where there are clear intentional errors but instead shows this one: 
![docx document](https://user-images.githubusercontent.com/37506005/204110323-f0a3d1c0-4f9c-4111-8838-2248a3eee6ff.PNG)

**Comment by AndiBraimllari** [comment]
Should have been addressed in https://github.com/OpenCovenant/quill/pull/110. Feel free to close this issue if so.
