### ISSUE TITLE
Expand Arrow test on Cypress

### ISSUE THREAD

**Issue by AndersonCeci** [OpenCovenant/quill#130]
One of the cypress tests were one that clicks on expand arrow but when you run it on `npx cypress open` everything was alright and it passed the test.
When run on `npx cypress run` it failed all the time on electron 
But when you add `npx cypress run --browser chrome` 1/10 test cases it failed In chrome 
Below I'm showing the test code :
```js
    it('will click on the expand arrow and click on all suggestions and close it again', () => {

        cy.get("#editor > p > .typo").should("not.exist");
        cy.get("#editor").type("fshji ");
        cy.get('h3.bi-arrow-right-square').click();
        cy.get('button.suggestion').contains("afshi").click();
        cy.get("#editor").contains("afshi").should("exist");
        cy.get("#editor").clear();

        cy.get("#editor > p > .typo").should("not.exist");
        cy.get("#editor").type("fshji ");
        cy.get('h3.bi-arrow-right-square').click();
        cy.get('button.suggestion').contains("shaji").click();
        cy.get("#editor").contains("shaji").should("exist");
        cy.get('h3.bi-arrow-left-square').click();
        cy.get("#editor").clear();
    }); 
```
The error that cypress throws for running this is  : 
`AssertionError: Timed out retrying after 4000ms: Expected to find element: 'h3.bi-arrow-left-square', but never found it."`

**Comment by AndiBraimllari** [comment]
If consider this issue to be solved feel free to close it.
