### ISSUE TITLE
Live server freezes it causes browser to crash and sometime the computer too

### ISSUE THREAD

**Issue by AndersonCeci** [OpenCovenant/quill#137]
On live server penda.info when you paste something and select it all,delete it, and paste it again it freezes the browser and the computer sometimes it just freezes by itself even when you are not using it

**Comment by AndiBraimllari** [comment]
Should be fixed now.

Feel free to try the changes and close the issue if it seems to have been fixed.

**Comment by AndersonCeci** [comment]
Yep all good now
