### ISSUE TITLE
highlight selected marking?

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#146]
When mousing over or clicking on a marking in the editor, perhaps we should highlight the corresponding marking from the right (or below in mobile)?

**Comment by AndersonCeci** [comment]
I agree it gives the user a great idea where the mistake is if it is a very long text or highlights it when a number of words are met and you avoid the highlight on simple texts

**Comment by AndiBraimllari** [comment]
An initial implementing has been merged, further refinements are required.
