### ISSUE TITLE
remove the placeholder after going back to the editor with markings after attempting to upload a file

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#147]
After writing some text in the editor that generate a marking, clicking on the toggle to upload a document, and then going back to the editor, you will see the placeholder along with the written text.

**Comment by AndiBraimllari** [comment]
Can you @AndersonCeci confirm whether this is fixed? Feel free to close this if so.

**Comment by AndersonCeci** [comment]
> Can you @AndersonCeci confirm whether this is fixed? Feel free to close this if so.

Yep this is fixed closing it
