### ISSUE TITLE
the text markings on the right includes HTML if the user clicks on uploading a document 

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#148]
After writing some text in the editor that generate a marking and clicking on the toggle to upload a document, the user will see that the text markings will also include HTML.

**Comment by AndiBraimllari** [comment]
Probably due to `this.processedText.text` in `HomeComponent.getTextOfTextMarking` containing actual HTML and not simple text.

**Comment by AndiBraimllari** [comment]
Can you @AndersonCeci confirm whether this is fixed? Feel free to close it if so.

**Comment by AndersonCeci** [comment]
Everything looks fine closed this issue
