### ISSUE TITLE
"karaktere" number doesn't go 0 after deleting all text

### ISSUE THREAD

**Issue by AndersonCeci** [OpenCovenant/quill#157]
When writing on the text box and after u select all and delete the text the "karaktere" number stays the same only "fjale" and "shenjime" goes to 0

**Comment by AndiBraimllari** [comment]
True, good catch!
Feel free to create a PR to address this if you have an idea how to solve it.

**Comment by AndiBraimllari** [comment]
Consider closing if you think it is fixed in #158
