### ISSUE TITLE
refine "Clear Editor" button in mobile view

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#183]
The "x" icon seems to be quite close to the right border on mobile view, it evidently needs some refining. 
![Screenshot from 2023-07-11 23-25-54](https://github.com/OpenCovenant/quill/assets/11479070/da780bd7-54f0-4c65-b0f6-0bb7c065e0f3)

**Comment by Kledis98** [comment]
Assigning myself here !
