### ISSUE TITLE
bug in storing written texts in the history

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#198]
1. write a space in the editor, immediately delete it
2. wait (I guess > 15 seconds), an empty text will be added to the history of the written texts

TODO: investigate and possible avoid storing text with whitespaces?

**Comment by AndiBraimllari** [comment]
I believe this has been updated in https://github.com/OpenCovenant/quill/pull/223 with a test added in https://github.com/OpenCovenant/quill/pull/235.

Can you please double check whether this bug still happens @AndersonCeci? If not then let's close this issue.

**Comment by AndersonCeci** [comment]
This seems to be fixed closing it
