### ISSUE TITLE
frozen animation on the copy button in the editor when copying empty editor

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#258]

**Comment by AndiBraimllari** [comment]
Steps to reproduce bug:
- Go to the page
- click on the copy to clipboard button
- you will notice that the icon changes, and it doesn't revert, as it would revert if the editor had any text in it

Therefore the bug is to not have this button be stuck in this "intermediate" state.

**Comment by Kledis98** [comment]
Solved !
