### ISSUE TITLE
Uploading  the same file for the second time

### ISSUE THREAD

**Issue by Kledis98** [OpenCovenant/quill#260]
If you upload a file, then click X to remove the text, then after that try to upload the same file for the second time, the text is not shown on editor.

**Comment by AndiBraimllari** [comment]
Can you please double check whether that still happens? If it works fine feel free to close this issue then (unless you still want to keep this open?)
Can you also check other scenarios, i.e.uploading different files and so on.

**Comment by Kledis98** [comment]
Sure, I am going to check other scenarios.
