### ISSUE TITLE
improve position of the information icon, always right aligned?

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#314]
See attachment:
![Screenshot from 2023-10-09 02-28-52](https://github.com/OpenCovenant/quill/assets/11479070/9db66bf8-069d-4942-a873-9040a66471db)
I believe it would be better if it would be always on the right? As of now, I believe you will always see it in the right due to long texts, but for shorter texts it might be right at the end of such texts.

**Comment by AndiBraimllari** [comment]
Was implemented by @vaqueraoscar0, if you find the time can you @AndersonCeci, @Kledis98 please test this and close this?

**Comment by AndersonCeci** [comment]
> Was implemented by @vaqueraoscar0, if you find the time can you @AndersonCeci, @Kledis98 please test this and close this?

Looks good to me

**Comment by AndiBraimllari** [comment]
@AndersonCeci please check this again and close this issue if all is well.
