### ISSUE TITLE
revise use of BRs in the codebase

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#325]
See https://stackoverflow.com/a/1726079 and https://blog.hubspot.com/website/html-line-break

**Comment by Jeongseulho** [comment]
While modifying the BR tags, I've come across a question.

This is a photo with the BR tags removed(revise).
![image](https://github.com/OpenCovenant/quill/assets/110578739/9a2cbd6a-2ba9-426e-b404-1c0847408244)

And this is a photo including the BR tags(origin).
![image](https://github.com/OpenCovenant/quill/assets/110578739/33bb9955-27de-4b93-8305-01075a372adf)

Although I've removed the BR tags, the spacing seems sufficient. Do we need to add extra margin in place of the removed BR tags? If necessary, I can add margin along with removing the BR tags.

**Comment by AndiBraimllari** [comment]
Hey, the main goal of this issue is to remove the misuse of BRs (see both links in the desription) and replace it with the appropriate element (which might be just adding padding), therefore the page should look the same as after finishing this ticket.
If you'd like to update the padding visually, we can discuss that in another issue.

**Comment by AndiBraimllari** [comment]
Also, I think there are more (probably misused) BRs all over different components.

**Comment by Jeongseulho** [comment]
Certainly, I have noted your request Thank you

**Comment by AndiBraimllari** [comment]
Noticed that we have 2 BRs in `src/app/home/home.component.html` in lines 547, 548, should we address these as well @Jeongseulho?

**Comment by AndiBraimllari** [comment]
Can you please take over here @Kledis98, just a few BRs to be addressed I think.

**Comment by AndiBraimllari** [comment]
Can you please double check if there are any other such BRs, and close this issue if not? @Kledis98

**Comment by Kledis98** [comment]
Checked it and there are not any other BRs. I will close the issue.
