### ISSUE TITLE
breaking highlighting of markings

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#327]
Write a text with some typos, highlight one of those, choose a suggestion from the highlighted marking, now trying to highlight any other marking will not work.

**Comment by AndiBraimllari** [comment]
Write a Cypress test for this as well.

**Comment by AndiBraimllari** [comment]
Think this was addressed initially in https://github.com/OpenCovenant/quill/pull/351 and then in https://github.com/OpenCovenant/quill/pull/374, can you confirm @vaqueraoscar0 ? Also, can you @AndersonCeci please test this?

**Comment by AndersonCeci** [comment]
I tested it and everything appears to be functioning well. Therefore, I'm closing it.
