### ISSUE TITLE
live text of "duke lexuar shkrimin..."

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#350]
The text "duke lexuar shkrimin..." can be updated to "duke lexuar shkrimin.", "duke lexuar shkrimin..", "duke lexuar shkrimin..." while loading. Small improvement that makes it a bit more "lively".

**Comment by AndiBraimllari** [comment]
Think we have a good solution here, can you @AndersonCeci check this out? Any suggestions for improvement?

**Comment by AndersonCeci** [comment]
> Think we have a good solution here, can you @AndersonCeci check this out? Any suggestions for improvement?

is this also added for mobile? or am I missing something

**Comment by AndiBraimllari** [comment]
I think so. If everything is fine here, we can close this, and then try to improve these cards by perhaps adding illustrations and so on.
