### ISSUE TITLE
Markings of the same typos on editor are lost if user clicks 'X' . Tests must be added too.

### ISSUE THREAD

**Issue by Kledis98** [OpenCovenant/quill#352]
[Screencast from 27.10.23 06:36:27.MD CEST.webm](https://github.com/OpenCovenant/quill/assets/119816628/97649a1e-1b8c-403f-b98f-6f5875aa4899)

**Comment by AndiBraimllari** [comment]
Think this was solved by @vaqueraoscar0, can you please double check this @AndersonCeci ? I'll then close this issue if so.

**Comment by AndersonCeci** [comment]
It seems to be fixed everything working fine
