### ISSUE TITLE
when dismissing markings, the timeout is not reset, but when applying suggestions, the timeout is reset 

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#368]

**Comment by AndiBraimllari** [comment]
Is this fixed @vaqueraoscar0? Can you @AndersonCeci please test this, so we can close it if all seems fine.

**Comment by AndersonCeci** [comment]
Looking fine , looking good 👍

**Comment by AndiBraimllari** [comment]
Please test this again and then close it if all is good.
