### ISSUE TITLE
consider using CSS nesting

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#383]
On the existing code. See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting

**Comment by AndiBraimllari** [comment]
Any update here?

**Comment by Kledis98** [comment]
Working on this one...

**Comment by AndiBraimllari** [comment]
Implemented and reverted, see https://github.com/OpenCovenant/quill/issues/421
We might add nested styling if we utilize Sass or so. Closing this one here basically because it is a duplicate of #421
