### ISSUE TITLE
dark mode button slides to the left on page load

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#396]
Think this happens more often locally than in prod, but it still happens. Simply reload the home page locally, and you'll see a black circle quickly move near the middle of the page to the left.

**Comment by Kledis98** [comment]
Sometimes it is not just that black cirle, if you reload the page continuously, the navbar with all the elements is flickering.  The black circle happens most of the times. I will try to solve this. Is there any thing where should I focus ?

**Comment by Kledis98** [comment]
I think the black circle has to do with transition property.

**Comment by AndiBraimllari** [comment]
Think it is due to the initial CSS on page load (which I think includes the transition you mention), that has to be changed, but the behavior after load has to be the same.

**Comment by AndiBraimllari** [comment]
Change is merged and deployed, please test this @Kledis98, @AndersonCeci and close it if it looks good.

**Comment by AndersonCeci** [comment]
> Change is merged and deployed, please test this @Kledis98, @AndersonCeci and close it if it looks good.

Looking Good
