### ISSUE TITLE
add shortcuts

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#407]
Adding shortcuts not only may make it more straightforward for the user to interact with the page, but also in some cases may improve a11y.

Current ideas for shortcuts:

- h/H : open the dialog of written texts (history of written texts)
- c/C : copy the text in the editor
- 1, 2, 3, ... : apply the n-th (indexing starting from 1) suggestion of the first/top-most marking.
- Shift + 1, 2, 3, ... : highlight the n-th marking (indexing starting from 1)
- d : dismiss the first/top-most marking

We can also add a shortcut for opening the off-canvas component, opening the settings page, toggling dark mode and so on.

I guess ideally we also create a page (linked in the off-canvas component) that describes these to the user.

Open to suggestions.

**Comment by AndersonCeci** [comment]
When the text is highlighted, use the up and down arrow keys to move between markings. Pressing the down arrow will take you to the next marking, while pressing the up arrow will take you to the previous marking. The text will remain highlighted.

**Comment by AndiBraimllari** [comment]
Yea perhaps we can do something with the arrow up/down buttons. Btw what are you referring to with highlighted text?

Any other ideas?

**Comment by AndiBraimllari** [comment]
Please go to the `/shortcuts` page, test those and if there's no issue, please close this.

**Comment by AndersonCeci** [comment]
Everything looks good closing this
