### ISSUE TITLE
bolden "penda" header text in navigation bar on hover

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#418]
make it a bit larger, to signify that it is clickable, nothing exaggerated, other forms of "animation" or emphasizing it are welcome

**Comment by Tonykimanthi** [comment]
Hey AndiBraimllari,
I would like to help fix the **navigation bar** `on hover` issue. Please assign me.

**Comment by AndiBraimllari** [comment]
Hey, sure!
Basically what we're looking for is for the font-weight (or similar attribute) of the "penda" text in the header, should slowly increase (lightly) on hover, and should as slowly revert back when moving the mouse away. The idea is that it should be obvious to the user that this text is clickable.
<img width="76" alt="nvgbar" src="https://github.com/OpenCovenant/quill/assets/11479070/c0a30210-86a5-4d30-b3a1-e353aa740dce">
Assigned it to you, let me know if you need any help :)

**Comment by Tonykimanthi** [comment]
I have an issue installing the dependencies

**Comment by AndiBraimllari** [comment]
This is also solved by @Tonykimanthi, closing it.
