### ISSUE TITLE
Cypress test for #437

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#438]

**Comment by AndiBraimllari** [comment]
I believe you @AndersonCeci added the test for it here, https://github.com/OpenCovenant/quill/pull/443 ? Please double check and close this issue if so.

**Comment by AndersonCeci** [comment]
> I believe you @AndersonCeci added the test for it here, https://github.com/OpenCovenant/quill/pull/443 ? Please double check and close this issue if so.

Yep this is completed
