### ISSUE TITLE
refactor all overridden Bootstrap classes

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#445]
Check wherever we might have overridden any of them and extract that styling to existing/new classes.

**Comment by AndiBraimllari** [comment]
You've already done this a few times @AndersonCeci. Can you please double check and then close this if you won't find any overridden Bootstrap classes?

**Comment by AndersonCeci** [comment]
File Home.component.css
- _line 13 `.card-header` its a bootsrap class_
- _line 25  `.card-body`_
- _line 304 `.text-reset`_
- _line 144 `.list-group-item`_
- _line 277 `.bi-stars`_

File profile.component.css
- _line 7 `.card`_

**Comment by AndiBraimllari** [comment]
Awesome, thank you, I'll try to address these.
