### ISSUE TITLE
shorten heights - mobile only

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#490]
Shorten the white space height between the nav bar and editor, as well as the white space height between the editor and the list of markings. Rationale is that on page load, more elements are immediately visible.

**Comment by malik-na** [comment]
hey!
I can fix this. Please assign it to me.

**Comment by AndiBraimllari** [comment]
Hey, sure!
Basically, we're trying to shorten the areas marked in purple lines, for mobile only.
Feel free to create a PR and post screenshots with the proposed changes.
![shorten-headers](https://github.com/user-attachments/assets/51e5891c-2728-4346-a662-eaec84e1f822)

**Comment by AndiBraimllari** [comment]
Hey, any update here?

**Comment by AndiBraimllari** [comment]
Can you please have a look @AndersonCeci when you find time?

**Comment by AndersonCeci** [comment]
> Can you please have a look @AndersonCeci when you find time?

Sure

**Comment by malik-na** [comment]
> Hey, any update here?

Hey! Sorry about that. I'm not keeping well :(

**Comment by AndiBraimllari** [comment]
> > Hey, any update here?
> 
> Hey! Sorry about that. I'm not keeping well :(

All good, best of luck!

**Comment by AndiBraimllari** [comment]
Thanks for addressing this @AndersonCeci! Please double check it and feel free to close it.

**Comment by AndersonCeci** [comment]
All good
