### ISSUE TITLE
cannot leave the writing focus (clicking Done doesn't work) in some later iPhones

### ISSUE THREAD

**Issue by AndiBraimllari** [OpenCovenant/quill#62]

**Comment by AndiBraimllari** [comment]
I cannot seem to reproduce this, could you @AndersonCeci please also try it out?

**Comment by AndersonCeci** [comment]
> I cannot seem to reproduce this, could you @AndersonCeci please also try it out?

I checked and tested it on multiple devices everything looks good closing this issue
