### ISSUE TITLE
Investigate Main Branch Sync Option

### ISSUE THREAD

**Issue by stackoversnow** [OpenCovenant/quill#91]
![sync](https://user-images.githubusercontent.com/99611775/200171187-4e57078f-24a7-4cfa-b900-8d467ba993af.jpg)

Similar to the screenshot above, research/investigate how this can be applied to this repo, as a good mechanism to prevent issues such as merge conflicts and other ones. 
Come up with a solution to have something like this, or note why we can't have it.

**Comment by AndiBraimllari** [comment]
Valid suggestion, this should be now available, along with auto-merge. Feel free to close the issue if the mentioned changes have been made.

**Comment by AndiBraimllari** [comment]
This has been added and used, let me know if you'd like to change something, otherwise feel free to close this issue.

**Comment by stackoversnow** [comment]
Looks good 👍
